spring.application.name=feedback-backend

# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6rppa7fte5s73erhb6g-a.oregon-postgres.render.com:5432/feedback_t6zr
spring.datasource.username=feedback_t6zr_user
spring.datasource.password=MN4pnMO9hzVqKS84RerYhu3qS4h3Dklc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=${PORT:8080}